version: "3.9"

services:
  app:
    build: .
    container_name: mr-notifier-app
    volumes:
      - .:/app
      - /app/tmp
    working_dir: /app
    command: air
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

  postgres:
    image: postgres:15
    container_name: mr-notifier-postgres
    env_file:
      - .env

  redis:
    image: redis:7
    container_name: mr-notifier-redis
    ports:
      - "6379:6379"